Importar recursos y librerias

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

Recursos necesarios de trabajo

In [3]:
rutaArchivo='examen1.xlsx' #Archivo a trabajar
hoja='examen1' #hoja del archivo

Vincular el recurso donde se encuentran almacenados los datos en un documento excel, así como ver la información de los campos registrados

In [4]:
data= pd.read_excel(rutaArchivo,sheet_name=hoja)
#Eliminar campo de conteo
data=data.drop(data.columns[[0,1]],axis=1)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   inicio      517 non-null    object
 1   final       517 non-null    object
 2   nota        517 non-null    float64
 3   p1          517 non-null    float64
 4   p2          517 non-null    float64
 5   p3          517 non-null    float64
 6   p4          517 non-null    float64
 7   p5          517 non-null    float64
 8   p6          517 non-null    object
 9   p7          517 non-null    float64
 10  p8          517 non-null    float64
 11  p9          517 non-null    float64
 12  p10         517 non-null    float64
 13  grupo       517 non-null    int64
 14  profesor    517 non-null    object
 15  jornada     517 non-null    object
 16  diferencia  517 non-null    object
 17  delta       517 non-null    float64
dtypes: float64(11), int64(1), object(6)
memory usage: 72.8+ KB

In [18]:
#Filtrar jornada día orden ascendente por docente
base2=data[data['jornada']=='Día'].sort_values(['profesor'],ascending=(True))
base2

,inicio,final,nota,p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,grupo,profesor,jornada,diferencia,delta
281,09:24:00,10:37:00,2.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.5,0.5,0.5,11,Alfonso Peña Suarez,Día,1:13:00,0.050694
376,09:11:00,09:53:00,2.0,0.0,0.0,0.5,0.5,0.0,0,0.0,0.5,0.0,0.5,11,Alfonso Peña Suarez,Día,0:42:00,0.029167
73,09:12:00,09:47:00,4.0,0.5,0.0,0.5,0.5,0.5,0,0.5,0.5,0.5,0.5,11,Alfonso Peña Suarez,Día,0:35:00,0.024306
377,09:26:00,10:36:00,2.5,0.0,0.0,0.0,0.0,0.5,0,0.5,0.5,0.5,0.5,11,Alfonso Peña Suarez,Día,1:10:00,0.048611
394,09:26:00,10:34:00,4.5,0.5,0.5,0.5,0.5,0.5,0.5,0.0,0.5,0.5,0.5,11,Alfonso Peña Suarez,Día,1:08:00,0.047222
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
328,09:12:00,10:30:00,3.0,0.5,0.0,0.5,0.5,0.0,0.5,0.0,0.0,0.5,0.5,32,Oscar David Murcia Portilla,Día,1:18:00,0.054167
471,09:27:00,10:34:00,1.0,0.5,0.0,0.0,0.5,0.0,0,0.0,0.0,0.0,0.0,32,Oscar David Murcia Portilla,Día,1:07:00,0.046528
468,09:11:00,10:05:00,1.5,0.0,0.0,0.5,0.0,0.0,0,0.5,0.0,0.0,0.5,32,Oscar David Murcia Portilla,Día,0:54:00,0.037500
310,09:11:00,10:05:00,1.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.5,0.0,0.5,32,Oscar David Murcia Portilla,Día,0:54:00,0.037500
474,09:11:00,10:16:00,1.5,0.0,0.0,0.0,0.0,0.5,0,0.0,0.5,0.0,0.5,32,Oscar David Murcia Portilla,Día,1:05:00,0.045139

In [22]:
#Guardar por diferente tipo
base2.to_excel('jornadaDia.xlsx',sheet_name="Dia")
base2.to_csv('jornadaDia.csv',sep=",")

In [23]:
#Notas máximas
base2[['nota','p1','p2','p3']].max()

nota    5.0
p1      0.5
p2      0.5
p3      0.5
dtype: float64

In [30]:
data[['profesor'],]

TypeError: '(['profesor'], ['nota'])' is an invalid key

Estadistica Descriptiva

In [18]:
data.describe()

,nota,p1,p2,p3,p4,p5,p7,p8,p9,p10,grupo,delta
count,517.000000,517.000000,517.00000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000
mean,1.919729,0.179884,0.16441,0.166344,0.214700,0.198259,0.163443,0.226306,0.233075,0.234043,15.820116,0.038520
std,1.122289,0.240199,0.23512,0.235816,0.247735,0.244824,0.234765,0.249116,0.249668,0.249732,10.065124,0.011647
min,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.012500
25%,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.000000,0.029167
50%,2.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,0.037500
75%,2.500000,0.500000,0.50000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,25.000000,0.047222
max,5.000000,0.500000,0.50000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,33.000000,0.068750

In [54]:
#pd.crosstab(index=data['profesor'],columns=[data['nota'],data['p1']])
#profesores=data['profesor'].unique()

pd.crosstab(index=['profesor'],columns=data['nota'].mean())

ValueError: If using all scalar values, you must pass an index